### ISSUE TITLE
Не работают коссольные команды

### ISSUE THREAD

**Issue by axklim** [ElisDN/yii2-demo-shop#8]
```
vagrant@gradmash:/app$ ./yii
Exception 'Exception' with message 'Invalid MailChimp API key `` supplied.'

in /app/vendor/drewm/mailchimp-api/src/MailChimp.php:43

Stack trace:
#0 /app/common/bootstrap/SetUp.php(95): DrewM\MailChimp\MailChimp->__construct('')
#1 [internal function]: common\bootstrap\SetUp->common\bootstrap\{closure}(Object(yii\di\Container), Array, Array)
#2 /app/vendor/yiisoft/yii2/di/Container.php(163): call_user_func(Object(Closure), Object(yii\di\Container), Array, Array)
#3 /app/vendor/yiisoft/yii2/di/Container.php(456): yii\di\Container->get('shop\\services\\n...')
#4 /app/vendor/yiisoft/yii2/di/Container.php(370): yii\di\Container->resolveDependencies(Array, Object(ReflectionClass))
#5 /app/vendor/yiisoft/yii2/di/Container.php(156): yii\di\Container->build('shop\\useCases\\m...', Array, Array)
#6 /app/vendor/yiisoft/yii2/di/Container.php(456): yii\di\Container->get('shop\\useCases\\m...')
#7 /app/vendor/yiisoft/yii2/di/Container.php(370): yii\di\Container->resolveDependencies(Array, Object(ReflectionClass))
#8 /app/vendor/yiisoft/yii2/di/Container.php(156): yii\di\Container->build('console\\control...', Array, Array)
#9 /app/vendor/yiisoft/yii2/BaseYii.php(340): yii\di\Container->get('console\\control...', Array)
#10 /app/vendor/yiisoft/yii2/base/Module.php(638): yii\BaseYii::createObject('console\\control...', Array)
#11 /app/vendor/yiisoft/yii2/base/Module.php(591): yii\base\Module->createControllerByID('role')
#12 /app/vendor/yiisoft/yii2/console/controllers/HelpController.php(196): yii\base\Module->createController('')
#13 /app/vendor/yiisoft/yii2/console/controllers/HelpController.php(288): yii\console\controllers\HelpController->getCommandDescriptions()
#14 /app/vendor/yiisoft/yii2/console/controllers/HelpController.php(67): yii\console\controllers\HelpController->getDefaultHelp()
#15 [internal function]: yii\console\controllers\HelpController->actionIndex(NULL)
#16 /app/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#17 /app/vendor/yiisoft/yii2/base/Controller.php(156): yii\base\InlineAction->runWithParams(Array)
#18 /app/vendor/yiisoft/yii2/console/Controller.php(128): yii\base\Controller->runAction('', Array)
#19 /app/vendor/yiisoft/yii2/base/Module.php(523): yii\console\Controller->runAction('', Array)
#20 /app/vendor/yiisoft/yii2/console/Application.php(180): yii\base\Module->runAction('', Array)
#21 /app/vendor/yiisoft/yii2/console/Application.php(147): yii\console\Application->runAction('', Array)
#22 /app/vendor/yiisoft/yii2/base/Application.php(380): yii\console\Application->handleRequest(Object(yii\console\Request))
#23 /app/yii(27): yii\base\Application->run()
#24 {main}
```

**Comment by halabooda** [comment]
В файле .gitignore на первых строках записан файл yii, который и запускает консольные команды....
https://github.com/ElisDN/yii2-demo-shop/blob/master/.gitignore

вам нужно руками его скопировать в вашу дирректорию

**Comment by ElisDN** [comment]
@Maksclub Файл yii распаковывается командой `php init`. Дело не в нём.

**Comment by asyou99** [comment]
Добавьте ключ в конфиг и все будет ок. Было тоже самое после добавления ключа все стало на свои места

**Comment by ElisDN** [comment]
Fixed.
